const Map<String, String> commonRegions = {
  'US': 'United States',
  'GB': 'United Kingdom',
  'CA': 'Canada',
  'AU': 'Australia',
  'DE': 'Germany',
  'FR': 'France',
  'IT': 'Italy',
  'ES': 'Spain',
  'BR': 'Brazil',
  'MX': 'Mexico',
  'JP': 'Japan',
  'KR': 'South Korea',
  'IN': 'India',
  'NL': 'Netherlands',
  'SE': 'Sweden',
  'NO': 'Norway',
  'DK': 'Denmark',
  'FI': 'Finland',
  'PL': 'Poland',
  'PT': 'Portugal',
  'AT': 'Austria',
  'CH': 'Switzerland',
  'BE': 'Belgium',
  'IE': 'Ireland',
  'NZ': 'New Zealand',
  'ZA': 'South Africa',
  'AR': 'Argentina',
  'CL': 'Chile',
  'CO': 'Colombia',
  'RU': 'Russia',
};
